version: "3.9"

services:

  db:
    image: mysql
    container_name: shinsengumi_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - data_volume:/var/lib/mysql

  client:
    build:
      context: ./bot
      dockerfile: Dockerfile.dev
    container_name: shinsengumi_client
    networks: 
      - db
    depends_on:
      - db
    volumes: 
      - type: bind
        source: ./bot
        target: /home/node/shinsengumi
    environment: 
      MYSQL_ROOT_PASSWORD: password

volumes:
  data_volume:

networks:
  db:
    driver: bridge
    name: shinsengumi_db