version: "3.9"

services: 

  db:
    image: mysql:8.0.22
    container_name: shinsengumi_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - data_volume:/var/lib/mysql

  client:
    build:
      context: ./bot
    container_name: shinsengumi_client
    restart: always
    networks: 
      - db
    depends_on:
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: password

volumes:
  data_volume:

networks:
  db:
    driver: bridge
    name: shinsengumi_db
