version: "3.9"

services: 

  db:
    build:
      context: ./database
    container_name: shinsengumi_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data_volume:/var/lib/mysql

  client:
    build:
      context: ./bot
    container_name: shinsengumi_client
    restart: always
    networks: 
      - db
    depends_on:
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: password

  web:
    build:
      context: ./web
    container_name: shinsengumi_web
    restart: always

volumes:
  data_volume:

networks:
  db:
    driver: bridge
    name: shinsengumi_db
