version: "3.9"

services: 

  client:
    build:
      context: ./bot
    container_name: shinsengumi_client
    networks: 
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: password

  db:
    image: mysql
    container_name: shinsengumi_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: password

networks:
  db:
    driver: bridge
    name: shinsengumi_db